name: Build Dev Binaries

on:
  push:
    branches: ["**"]  # Chạy trên mọi nhánh

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  build_artifacts:
    name: Build Artifacts
    strategy:
      matrix:
        os: [windows-latest] # Chỉ giữ windows nếu bạn chỉ cần exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - id: toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get Version & Triple
        id: vars
        shell: bash
        run: |
          echo "version=$(cargo pkgid --package uggo | cut -d# -f2 | cut -d: -f2)" >> $GITHUB_OUTPUT
          echo "triple=$(rustc -vV | sed -n 's|host: ||p')" >> $GITHUB_OUTPUT

      - name: Build Release
        run: cargo build --package uggo --release

      - name: Rename & Prepare Artifacts
        shell: bash
        run: |
          npm install -g move-file-cli mkdirp
          mkdirp artifacts
          if [ "$RUNNER_OS" == "Windows" ]; then
            move-file target/release/uggo.exe artifacts/uggo-${{ steps.vars.outputs.version }}-${{ steps.vars.outputs.triple }}.exe
          else
            move-file target/release/uggo artifacts/uggo-${{ steps.vars.outputs.version }}-${{ steps.vars.outputs.triple }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uggo-${{ matrix.os }}
          path: artifacts/*
